version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      ignore:
          - dependency-name: "axum"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "axum-core"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "axum-extra"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "axum-test"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "axum_typed_multipart"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "bytes"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "headers"
            update-types:
                - "version-update:semver-major"
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "http"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "http-body"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "http-body-util"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "tokio"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "serde"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "serde_json"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "serde_urlencoded"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "tower-layer"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "tower-service"
            update-types:
                - "version-update:semver-patch"
          - dependency-name: "utoipa"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
