[workspace]
resolver = "2"
members = [
    "__test__",
    "package",
]

[workspace.dependencies]
axum = { version = "~0.8.1", features = ["multipart", "macros"] }
axum_typed_multipart = "~0.15.1"
jder_axum = { path = "./package" }
serde = { version = "^1.0.217", features = ["derive"] }
