[workspace]
resolver = "2"
members = [
    "__test__",
    "package",
]

[workspace.dependencies]
axum = { version = "~0.8.3", features = ["macros"] }
axum_typed_multipart =  "~0.16.0"
jder_axum = { path = "./package", features = ["all"] }
serde = { version = "^1", features = ["derive"] }
