disable_all_formatting = false
edition = "2024"
fn_params_layout = "Vertical"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 80
merge_derives = false
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 10
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = true
