[package]
name = "jder_axum"
version = "0.4.0"
authors = ["Alpheus Tang"]
edition = "2024"
description = """
A response builder for axum
"""
readme = "README.md"
homepage = "https://github.com/alpheustangs/jder_axum"
repository = "https://github.com/alpheustangs/jder_axum"
license = "MIT"
keywords = [
    "jder",
    "axum",
    "json",
    "response",
    "util",
]
categories = [
    "parser-implementations",
    "web-programming",
]
include = [
    "src/*", 
    "Cargo.toml",
    "README.md",
]

[lib]
name = "jder_axum"
path = "src/lib.rs"

[dependencies]
axum ={ workspace = true }
axum-core = "~0.5.1"
axum-extra = "~0.10.0"
axum_typed_multipart = { workspace = true }
bytes = "^1.10.0"
serde = { workspace = true }
serde_json = "^1.0.139"
