[package]
name = "jder_axum"
version = "0.3.0"
authors = ["Alpheus Tang"]
edition = "2021"
description = """
A response builder for Axum
"""
readme = "README.md"
homepage = "https://github.com/alpheustangs/jder_axum"
repository = "https://github.com/alpheustangs/jder_axum"
license = "MIT"
keywords = [
    "jder",
    "axum",
    "json",
    "response",
    "util",
]
categories = [
    "parser-implementations",
    "web-programming",
]
include = [
    "src/*", 
    "Cargo.toml",
    "README.md",
]

[lib]
name = "jder_axum"
path = "src/lib.rs"

[dependencies]
axum = { version = "~0.7.7", features = ["multipart"] }
axum-core = "~0.4.5"
axum_typed_multipart = "~0.13.2"
bytes = "^1.8.0"
serde = { version = "^1.0.215", features = ["derive"] }
serde_json = "^1.0.133"
